spring.application.name=emma
spring.cache.type=simple

# MSSQL CONFIG
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Configuração do banco
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# JPA
spring.jpa.database-platform=org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.hibernate.ddl-auto=update

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Spring AI (OpenAI)
# Puxa o valor da variável de ambiente OPENAI_API_KEY
spring.ai.openai.api-key=${OPENAI_API_KEY}

# Configuração do segredo do JWT
api.emma.token.secret=Gui080606

server.port=8081
