CREATE TABLE reading (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date TIMESTAMP,
    description VARCHAR(500),
    humor VARCHAR(255),

    person_id BIGINT,
    CONSTRAINT fk_reading_person FOREIGN KEY (person_id) REFERENCES person(id)
);
