CREATE TABLE review (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(1200),

    reading_id BIGINT,
    CONSTRAINT fk_review_reading FOREIGN KEY (reading_id) REFERENCES reading(id)
);
